### ISSUE TITLE
python setup.py install command fails

### ISSUE THREAD

**Issue by EmilCreatePro** [julimueller/dtld_parsing#7]
When trying to run "python setup.py install" it gives me this error:

Traceback (most recent call last):
  File "setup.py", line 1, in <module>
    from setuptools import setup, find_packages
ImportError: No module named setuptools

Saw that some modules were updated to Python 3. 
Shouldn't we use the command "python3 setup.py install" instead in order to run it with python 3?

**Comment by julimueller** [comment]
Try
pip install setuptools && python setup.py install

Or 

pip3 install setuptools && python3 setup.py install

**Comment by EmilCreatePro** [comment]
Fixed 'setupmodules' error by using command:
sudo apt-get install python-setuptools

But other errors came when using command "python setup.py install" :

##############################################################  
File "build/bdist.linux-x86_64/egg/dtld_parsing/calibration.py", line 254
    def load_intrinsic_matrix(self, path: str):
                                        ^
SyntaxError: invalid syntax

byte-compiling build/bdist.linux-x86_64/egg/dtld_parsing/driveu_dataset.py to driveu_dataset.pyc
  File "build/bdist.linux-x86_64/egg/dtld_parsing/driveu_dataset.py", line 43
    def parse_object_dict(self, object_dict: dict):
                                           ^
SyntaxError: invalid syntax

byte-compiling build/bdist.linux-x86_64/egg/dtld_parsing/vehicle_data.py to vehicle_data.pyc
  File "build/bdist.linux-x86_64/egg/dtld_parsing/vehicle_data.py", line 27
    def parse_vehicle_data_dict(self, image_dict: dict):
                                                ^
SyntaxError: invalid syntax

creating build/bdist.linux-x86_64/egg/EGG-INFO
copying python/dtld_parsing.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying python/dtld_parsing.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying python/dtld_parsing.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying python/dtld_parsing.egg-info/not-zip-safe -> build/bdist.linux-x86_64/egg/EGG-INFO
copying python/dtld_parsing.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying python/dtld_parsing.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
creating dist
creating 'dist/dtld_parsing-1.0-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing dtld_parsing-1.0-py2.7.egg
creating /usr/local/lib/python2.7/dist-packages/dtld_parsing-1.0-py2.7.egg
Extracting dtld_parsing-1.0-py2.7.egg to /usr/local/lib/python2.7/dist-packages
  File "/usr/local/lib/python2.7/dist-packages/dtld_parsing-1.0-py2.7.egg/dtld_parsing/calibration.py", line 254
    def load_intrinsic_matrix(self, path: str):
                                        ^
SyntaxError: invalid syntax

  File "/usr/local/lib/python2.7/dist-packages/dtld_parsing-1.0-py2.7.egg/dtld_parsing/driveu_dataset.py", line 43
    def parse_object_dict(self, object_dict: dict):
                                           ^
SyntaxError: invalid syntax

  File "/usr/local/lib/python2.7/dist-packages/dtld_parsing-1.0-py2.7.egg/dtld_parsing/vehicle_data.py", line 27
    def parse_vehicle_data_dict(self, image_dict: dict):
                                                ^
SyntaxError: invalid syntax

Adding dtld-parsing 1.0 to easy-install.pth file

Installed /usr/local/lib/python2.7/dist-packages/dtld_parsing-1.0-py2.7.egg
Processing dependencies for dtld-parsing==1.0
Searching for pyyaml
Reading https://pypi.python.org/simple/pyyaml/
Downloading https://files.pythonhosted.org/packages/64/c2/b80047c7ac2478f9501676c988a5411ed5572f35d1beff9cae07d321512c/PyYAML-5.3.1.tar.gz#sha256=b8eac752c5e14d3eca0e6dd9199cd627518cb5ec06add0de9d32baeee6fe645d
Best match: PyYAML 5.3.1
Processing PyYAML-5.3.1.tar.gz
Writing /tmp/easy_install-gMFmnG/PyYAML-5.3.1/setup.cfg
Running PyYAML-5.3.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-gMFmnG/PyYAML-5.3.1/egg-dist-tmp-CPbM5d
In file included from ext/_yaml.c:596:0:
ext/_yaml.h:2:10: fatal error: yaml.h: No such file or directory
 #include <yaml.h>
          ^~~~~~~~
compilation terminated.
Error compiling module, falling back to pure Python
zip_safe flag not set; analyzing archive contents...
Moving PyYAML-5.3.1-py2.7-linux-x86_64.egg to /usr/local/lib/python2.7/dist-packages
Adding PyYAML 5.3.1 to easy-install.pth file

Installed /usr/local/lib/python2.7/dist-packages/PyYAML-5.3.1-py2.7-linux-x86_64.egg
Searching for opencv-python
Reading https://pypi.python.org/simple/opencv-python/
Downloading https://files.pythonhosted.org/packages/f6/ca/33ef6ffe0f6f7a825febdbf655c192f30d0f59d40f23b647d08a1c2a26c5/opencv_python-4.2.0.32-cp27-cp27mu-manylinux1_x86_64.whl#sha256=db1d49b753e6e6c76585f21d09c7e9812176732baa9bddb64bc2fc6cd24d4179
Best match: opencv-python 4.2.0.32
Processing opencv_python-4.2.0.32-cp27-cp27mu-manylinux1_x86_64.whl
Installing opencv_python-4.2.0.32-cp27-cp27mu-manylinux1_x86_64.whl to /usr/local/lib/python2.7/dist-packages
writing requirements to /usr/local/lib/python2.7/dist-packages/opencv_python-4.2.0.32-py2.7-linux-x86_64.egg/EGG-INFO/requires.txt
Adding opencv-python 4.2.0.32 to easy-install.pth file

Installed /usr/local/lib/python2.7/dist-packages/opencv_python-4.2.0.32-py2.7-linux-x86_64.egg
Searching for numpy
Reading https://pypi.python.org/simple/numpy/
Downloading https://files.pythonhosted.org/packages/84/1e/ff467ac56bfeaea51d4a2e72d315c1fe440b20192fea7e460f0f248acac8/numpy-1.18.2.zip#sha256=e7894793e6e8540dbeac77c87b489e331947813511108ae097f1715c018b8f3d
Best match: numpy 1.18.2
Processing numpy-1.18.2.zip
Writing /tmp/easy_install-Nd7wu8/numpy-1.18.2/setup.cfg
Running numpy-1.18.2/setup.py -q bdist_egg --dist-dir /tmp/easy_install-Nd7wu8/numpy-1.18.2/egg-dist-tmp-bkVVqH
Traceback (most recent call last):
  File "setup.py", line 14, in <module>
    install_requires=required,
  File "/usr/lib/python2.7/dist-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 117, in do_egg_install
    cmd.run()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 437, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 679, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 726, in install_item
    self.process_distribution(spec, dist, deps)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 771, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 774, in resolve
    replace_conflicting=replace_conflicting
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1057, in best_match
    return self.obtain(req, installer)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1069, in obtain
    return installer(requirement)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 698, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 724, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 909, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1177, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1163, in run_setup
    run_setup(setup_script, args)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 253, in run_setup
    raise
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 166, in save_modules
    saved_exc.resume()
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 141, in resume
    six.reraise(type, exc, self._tb)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-Nd7wu8/numpy-1.18.2/setup.py", line 32, in <module>
    
RuntimeError: Python version >= 3.5 required.
################################################################

Running with _python3 setup.py install_ did work though!
-> Output: Finished processing dependencies for dtld-parsing==1.0

Will I run into problems in the future because I used **python3** instead of **python** ?

**Comment by julimueller** [comment]
As you can see in the output you are not using Python 3. The code can only be used in Python3 not in 2.7. Please set up a python3 virtual environment to test it, Google will help you if you do not have enough experience.

EDIT: Sorry read over your last sentence. Nope, i guess you will not. I updated the Readme.

**Comment by EmilCreatePro** [comment]
Thank you Julian for your fast response and help! :)
Very glad this was settled so fast
